(function(exports){

	exports.MAP = [
		'000000000000000000000000000000000000000000000000000000000000000000000000000',
		'0gggtttggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggg0',
		'0ggttggggghggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggg0',
		'0gggmgggssvvgggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggg0',
		'0ggmgggggsvvgggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggg0',
		'0gggggvgggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggg0',
		'0ggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggg0',
		'0ggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggg0',
		'0ggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggg0',
		'0gggggggggggggggggggggggggggggggmmmggggggggggggggggggggggggggggggggggggggg0',
		'0ggggggggggggggggggggggggggggmmmggmmmggggggggggggggggggggggggggggggggggggg0',
		'0gggggggggggggggggggggggggmmmggggggggggggggggggggggggggggggggggggggggggggg0',
		'0ggggggggggggggggggggggggmmmggggttgggggggggggggggggggggggggggggggggggggggg0',
		'0gggggggggggggggggggggggggmmgggggggggggggggggggggggggggggggggggggggggggggg0',
		'0ggggggggggggggggggggggggggmmmggggggsggggggggggggggggggggggggggggggggggggg0',
		'0ggggggggggggggggggggggggggggggggggsssgggggggggggggggggggggggggggggggggggg0',
		'0gggggggggggggggggggggggggggggggggssmmssgggggggggggggggggggggggggggggggggg0',
		'0ggggggggggggggggggggggggggggggggssmcmssgggggggggggggggggggggggggggggggggg0',
		'0gggggggggggggggggggggggggggggggggssmmssgggggggggggggggggggggggggggggggggg0',
		'0ggggggggggggggggggggggggggggggggggsssgggggggggggggggggggggggggggggggggggg0',
		'0gggggggggggggggggggggggggggggggggsggggggggggggggggggggggggggggggggggggggg0',
		'0ggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggg0',
		'0ggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggg0',
		'0ggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggg0',
		'0ggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggg0',
		'0ggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggg0',
		'0ggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggg0',
		'0ggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggg0',
		'0ggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggg0',
		'0ggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggg0',
		'0ggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggg0',
		'0ggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggg0',
		'0ggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggg0',
		'0ggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggg0',
		'0ggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggg0',
		'000000000000000000000000000000000000000000000000000000000000000000000000000'
	];

})(typeof exports === 'undefined'? this['mapInfo']={}: exports);

